import json
import multiprocessing
import sys
import time
from settings import BASE_PORT, DASHBOARD_PORT, PASS_SCHEDULE_FILE, SATELLITE_STARTUP_DELAY


def _satellite_worker(satellite_id: str, port: int) -> None:
    from src.satellite.server import SatelliteServer
    import logging

    logging.basicConfig(
        level=logging.INFO,
        format=f"%(asctime)s [%(levelname)s] %(message)s",
    )
    server = SatelliteServer(satellite_id=satellite_id, port=port)
    server.serve()


def _ground_station_worker(satellite_ports: dict[str, int], dashboard_port: int) -> None:
    import json as _json
    import logging
    import sys
    from typing import Any

    sys.path.insert(0, ".")
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
    logger = logging.getLogger(__name__)

    from src.ground_station.downlink import DownlinkManager, SimClock
    from src.ground_station.event_log import EventLog
    from src.ground_station.main import _build_file_info, _start_dashboard
    from src.ground_station.reporter import Reporter
    from src.ground_station.scheduler import Scheduler, load_pass_schedule
    from settings import DASHBOARD_PORT, PASS_SCHEDULE_FILE, POST_SIMULATION_IDLE_SECONDS, REPORT_OUTPUT_FILE, TIME_SCALE

    passes = load_pass_schedule(PASS_SCHEDULE_FILE)
    logger.info("[GS] Loaded %d passes", len(passes))

    scheduler = Scheduler(passes)
    event_log = EventLog()
    downlink = DownlinkManager(scheduler=scheduler, satellite_ports=satellite_ports, event_log=event_log)

    file_info = _build_file_info(list(satellite_ports.keys()))
    for sat_id, files in file_info.items():
        inventory = {
            fid: {
                "priority": meta["priority"],
                "total_chunks": meta["total_chunks"],
                "pending": list(range(1, meta["total_chunks"] + 1)),
            }
            for fid, meta in files.items()
        }
        scheduler.update_inventory(sat_id, inventory)

    sim_clock = SimClock(start=0.0, scale=TIME_SCALE)
    sim_state: dict[str, Any] = {"is_running": True, "current_satellite": None}

    _start_dashboard(scheduler, event_log, sim_clock, sim_state, port=dashboard_port)

    logger.info("[GS] Starting simulation (TIME_SCALE=%.1f)", TIME_SCALE)
    downlink.run(sim_clock)
    sim_state["is_running"] = False
    logger.info("[GS] Simulation complete")

    reporter = Reporter(passes=passes, satellite_file_info=file_info)
    report = reporter.generate(events=event_log.all(), confirmed=downlink._confirmed)

    logger.info("[GS] Report written to %s", REPORT_OUTPUT_FILE)
    print(_json.dumps(report, indent=2))

    if POST_SIMULATION_IDLE_SECONDS > 0:
        import time as _time
        logger.info(
            "[GS] Dashboard staying up for %ds — http://localhost:%d/docs",
            POST_SIMULATION_IDLE_SECONDS,
            dashboard_port,
        )
        _time.sleep(POST_SIMULATION_IDLE_SECONDS)


def _discover_satellites() -> list[str]:
    """Reads the pass schedule and returns unique satellite IDs sorted alphabetically."""
    with open(PASS_SCHEDULE_FILE) as f:
        schedule = json.load(f)
    ids = sorted({data["satellite_id"] for data in schedule.values()})
    return ids


def generate_docker_compose(satellite_ids: list[str], satellite_ports: dict[str, int]) -> str:
    """Generates the content of docker-compose.yml dynamically."""
    services_yaml = []
    for sat_id in satellite_ids:
        port = satellite_ports[sat_id]
        services_yaml.append(f"""  {sat_id}:
    build: .
    command: python -m src.satellite.main --id {sat_id} --port {port}
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.connect(('localhost',{port})); s.close()"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 2s
    networks:
      - downlink_net""")

    satellite_hosts = {sat_id: sat_id for sat_id in satellite_ids}
    ports_json = json.dumps(satellite_ports)
    hosts_json = json.dumps(satellite_hosts)

    depends_on_yaml = []
    for sat_id in satellite_ids:
        depends_on_yaml.append(f"""      {sat_id}:
        condition: service_healthy""")
    depends_on_str = "\n".join(depends_on_yaml)

    satellites_section = "\n\n".join(services_yaml)

    compose_template = f"""# This file is dynamically generated by run.py. Do not edit manually.
# To regenerate or launch:
#   python run.py --generate-docker
#   python run.py --docker
services:

{satellites_section}

  ground_station:
    build: .
    command: >
      python -m src.ground_station.main
      --satellite-ports '{ports_json}'
      --satellite-hosts '{hosts_json}'
    depends_on:
{depends_on_str}
    ports:
      - "{DASHBOARD_PORT}:{DASHBOARD_PORT}"
    networks:
      - downlink_net

networks:
  downlink_net:
    driver: bridge
"""
    return compose_template


def main() -> None:
    import argparse
    import subprocess

    parser = argparse.ArgumentParser(description="Simulation Launcher")
    parser.add_argument(
        "--docker",
        action="store_true",
        help="Generate docker-compose.yml and launch the simulation inside Docker containers",
    )
    parser.add_argument(
        "--generate-docker",
        action="store_true",
        help="Only generate the docker-compose.yml file based on config and exit",
    )
    args = parser.parse_args()

    satellite_ids = _discover_satellites()
    satellite_ports = {sat_id: BASE_PORT + i + 1 for i, sat_id in enumerate(satellite_ids)}

    if args.generate_docker or args.docker:
        compose_content = generate_docker_compose(satellite_ids, satellite_ports)
        with open("docker-compose.yml", "w") as f:
            f.write(compose_content)
        print("Successfully generated/updated docker-compose.yml")
        if args.generate_docker:
            return

    if args.docker:
        print("Launching simulation in Docker Compose...")
        try:
            subprocess.run(["docker", "compose", "up", "--build", "--abort-on-container-exit"], check=True)
        except KeyboardInterrupt:
            print("Stopping Docker containers...")
            subprocess.run(["docker", "compose", "down"])
        except subprocess.CalledProcessError as e:
            print(f"Docker Compose failed: {e}")
        return

    print(f"Satellites discovered: {satellite_ids}")
    print(f"Port assignments: {satellite_ports}")

    processes: list[multiprocessing.Process] = []

    for sat_id, port in satellite_ports.items():
        p = multiprocessing.Process(
            target=_satellite_worker,
            args=(sat_id, port),
            name=sat_id,
            daemon=True,
        )
        p.start()
        processes.append(p)
        print(f"Started {sat_id} on port {port} (pid={p.pid})")

    print(f"Waiting {SATELLITE_STARTUP_DELAY}s for satellites to bind...")
    time.sleep(SATELLITE_STARTUP_DELAY)

    gs_process = multiprocessing.Process(
        target=_ground_station_worker,
        args=(satellite_ports, DASHBOARD_PORT),
        name="ground_station",
    )
    gs_process.start()
    print(f"Started ground_station (pid={gs_process.pid})")
    print(f"Dashboard: http://localhost:{DASHBOARD_PORT}/docs")

    gs_process.join()
    print("Ground station finished. Terminating satellite processes...")

    for p in processes:
        p.terminate()
        p.join()

    print("All processes done.")



if __name__ == "__main__":
    main()
